/*
 * generated by Xtext 2.12.0
 */
package it.unibz.inf.ontouml.archive.ui.outline

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
class OntoUMLArchiveOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
