/**
 * generated by Xtext 2.12.0
 */
package it.unibz.inf.ontouml.archive.ide;

import it.unibz.inf.ontouml.archive.ide.AbstractOntoUMLArchiveIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class OntoUMLArchiveIdeModule extends AbstractOntoUMLArchiveIdeModule {
}
