/**
 * generated by Xtext 2.12.0
 */
package it.unibz.inf.ontouml.archive;

import it.unibz.inf.ontouml.archive.OntoUMLArchiveStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class OntoUMLArchiveStandaloneSetup extends OntoUMLArchiveStandaloneSetupGenerated {
  public static void doSetup() {
    new OntoUMLArchiveStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
