/**
 * generated by Xtext 2.12.0
 */
package it.unibz.inf.ontouml.archive.ui;

import it.unibz.inf.ontouml.archive.ui.AbstractOntoUMLArchiveUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class OntoUMLArchiveUiModule extends AbstractOntoUMLArchiveUiModule {
  public OntoUMLArchiveUiModule(final AbstractUIPlugin arg0) {
    super(arg0);
  }
}
