/**
 * generated by Xtext 2.12.0
 */
package it.unibz.inf.ontouml.archive.ontoUMLArchive;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.OntoUMLArchiveFactory
 * @model kind="package"
 * @generated
 */
public interface OntoUMLArchivePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "ontoUMLArchive";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.unibz.it/inf/ontouml/archive/OntoUMLArchive";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "ontoUMLArchive";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  OntoUMLArchivePackage eINSTANCE = it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.OntoUMLArchivePackageImpl.init();

  /**
   * The meta object id for the '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.ModelImpl
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.OntoUMLArchivePackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Elments</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ELMENTS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.ModelElementImpl <em>Model Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.ModelElementImpl
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.OntoUMLArchivePackageImpl#getModelElement()
   * @generated
   */
  int MODEL_ELEMENT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Model Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.ClassImpl <em>Class</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.ClassImpl
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.OntoUMLArchivePackageImpl#getClass_()
   * @generated
   */
  int CLASS = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS__NAME = MODEL_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Is Abstract</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS__IS_ABSTRACT = MODEL_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Stereotype</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS__STEREOTYPE = MODEL_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Class</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_FEATURE_COUNT = MODEL_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.RelationshipImpl <em>Relationship</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.RelationshipImpl
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.OntoUMLArchivePackageImpl#getRelationship()
   * @generated
   */
  int RELATIONSHIP = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONSHIP__NAME = MODEL_ELEMENT__NAME;

  /**
   * The number of structural features of the '<em>Relationship</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONSHIP_FEATURE_COUNT = MODEL_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.AssociationImpl <em>Association</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.AssociationImpl
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.OntoUMLArchivePackageImpl#getAssociation()
   * @generated
   */
  int ASSOCIATION = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION__NAME = RELATIONSHIP__NAME;

  /**
   * The feature id for the '<em><b>Stereotype</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION__STEREOTYPE = RELATIONSHIP_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Association</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION_FEATURE_COUNT = RELATIONSHIP_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.RegularAssociationImpl <em>Regular Association</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.RegularAssociationImpl
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.OntoUMLArchivePackageImpl#getRegularAssociation()
   * @generated
   */
  int REGULAR_ASSOCIATION = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGULAR_ASSOCIATION__NAME = ASSOCIATION__NAME;

  /**
   * The feature id for the '<em><b>Stereotype</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGULAR_ASSOCIATION__STEREOTYPE = ASSOCIATION__STEREOTYPE;

  /**
   * The feature id for the '<em><b>From</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGULAR_ASSOCIATION__FROM = ASSOCIATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>To</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGULAR_ASSOCIATION__TO = ASSOCIATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Regular Association</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGULAR_ASSOCIATION_FEATURE_COUNT = ASSOCIATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.NaryAssociationImpl <em>Nary Association</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.NaryAssociationImpl
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.OntoUMLArchivePackageImpl#getNaryAssociation()
   * @generated
   */
  int NARY_ASSOCIATION = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NARY_ASSOCIATION__NAME = ASSOCIATION__NAME;

  /**
   * The feature id for the '<em><b>Stereotype</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NARY_ASSOCIATION__STEREOTYPE = ASSOCIATION__STEREOTYPE;

  /**
   * The feature id for the '<em><b>Ends</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NARY_ASSOCIATION__ENDS = ASSOCIATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Nary Association</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NARY_ASSOCIATION_FEATURE_COUNT = ASSOCIATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.AssociationEndImpl <em>Association End</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.AssociationEndImpl
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.OntoUMLArchivePackageImpl#getAssociationEnd()
   * @generated
   */
  int ASSOCIATION_END = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION_END__NAME = 0;

  /**
   * The feature id for the '<em><b>Multiplicity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION_END__MULTIPLICITY = 1;

  /**
   * The feature id for the '<em><b>End Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION_END__END_TYPE = 2;

  /**
   * The number of structural features of the '<em>Association End</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION_END_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.MultiplicityImpl <em>Multiplicity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.MultiplicityImpl
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.OntoUMLArchivePackageImpl#getMultiplicity()
   * @generated
   */
  int MULTIPLICITY = 8;

  /**
   * The feature id for the '<em><b>Lower</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICITY__LOWER = 0;

  /**
   * The feature id for the '<em><b>Upper</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICITY__UPPER = 1;

  /**
   * The number of structural features of the '<em>Multiplicity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICITY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.GeneralizationImpl <em>Generalization</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.GeneralizationImpl
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.OntoUMLArchivePackageImpl#getGeneralization()
   * @generated
   */
  int GENERALIZATION = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERALIZATION__NAME = RELATIONSHIP__NAME;

  /**
   * The feature id for the '<em><b>Super</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERALIZATION__SUPER = RELATIONSHIP_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Sub</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERALIZATION__SUB = RELATIONSHIP_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Generalization</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERALIZATION_FEATURE_COUNT = RELATIONSHIP_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.DependencyLinkImpl <em>Dependency Link</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.DependencyLinkImpl
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.OntoUMLArchivePackageImpl#getDependencyLink()
   * @generated
   */
  int DEPENDENCY_LINK = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCY_LINK__NAME = RELATIONSHIP__NAME;

  /**
   * The feature id for the '<em><b>From</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCY_LINK__FROM = RELATIONSHIP_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>To</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCY_LINK__TO = RELATIONSHIP_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Dependency Link</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCY_LINK_FEATURE_COUNT = RELATIONSHIP_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.GeneralizationSetImpl <em>Generalization Set</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.GeneralizationSetImpl
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.OntoUMLArchivePackageImpl#getGeneralizationSet()
   * @generated
   */
  int GENERALIZATION_SET = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERALIZATION_SET__NAME = MODEL_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Is Disjoint</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERALIZATION_SET__IS_DISJOINT = MODEL_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Is Complete</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERALIZATION_SET__IS_COMPLETE = MODEL_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Generalizations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERALIZATION_SET__GENERALIZATIONS = MODEL_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Generalization Set</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERALIZATION_SET_FEATURE_COUNT = MODEL_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.StereotypeImpl <em>Stereotype</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.StereotypeImpl
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.OntoUMLArchivePackageImpl#getStereotype()
   * @generated
   */
  int STEREOTYPE = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEREOTYPE__NAME = 0;

  /**
   * The number of structural features of the '<em>Stereotype</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEREOTYPE_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.Model#getElments <em>Elments</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elments</em>'.
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.Model#getElments()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Elments();

  /**
   * Returns the meta object for class '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.ModelElement <em>Model Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model Element</em>'.
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.ModelElement
   * @generated
   */
  EClass getModelElement();

  /**
   * Returns the meta object for the attribute '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.ModelElement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.ModelElement#getName()
   * @see #getModelElement()
   * @generated
   */
  EAttribute getModelElement_Name();

  /**
   * Returns the meta object for class '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.Class <em>Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Class</em>'.
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.Class
   * @generated
   */
  EClass getClass_();

  /**
   * Returns the meta object for the attribute '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.Class#isIsAbstract <em>Is Abstract</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is Abstract</em>'.
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.Class#isIsAbstract()
   * @see #getClass_()
   * @generated
   */
  EAttribute getClass_IsAbstract();

  /**
   * Returns the meta object for the containment reference '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.Class#getStereotype <em>Stereotype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Stereotype</em>'.
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.Class#getStereotype()
   * @see #getClass_()
   * @generated
   */
  EReference getClass_Stereotype();

  /**
   * Returns the meta object for class '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.Relationship <em>Relationship</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relationship</em>'.
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.Relationship
   * @generated
   */
  EClass getRelationship();

  /**
   * Returns the meta object for class '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.Association <em>Association</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Association</em>'.
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.Association
   * @generated
   */
  EClass getAssociation();

  /**
   * Returns the meta object for the containment reference '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.Association#getStereotype <em>Stereotype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Stereotype</em>'.
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.Association#getStereotype()
   * @see #getAssociation()
   * @generated
   */
  EReference getAssociation_Stereotype();

  /**
   * Returns the meta object for class '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.RegularAssociation <em>Regular Association</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Regular Association</em>'.
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.RegularAssociation
   * @generated
   */
  EClass getRegularAssociation();

  /**
   * Returns the meta object for the containment reference '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.RegularAssociation#getFrom <em>From</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>From</em>'.
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.RegularAssociation#getFrom()
   * @see #getRegularAssociation()
   * @generated
   */
  EReference getRegularAssociation_From();

  /**
   * Returns the meta object for the containment reference '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.RegularAssociation#getTo <em>To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>To</em>'.
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.RegularAssociation#getTo()
   * @see #getRegularAssociation()
   * @generated
   */
  EReference getRegularAssociation_To();

  /**
   * Returns the meta object for class '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.NaryAssociation <em>Nary Association</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Nary Association</em>'.
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.NaryAssociation
   * @generated
   */
  EClass getNaryAssociation();

  /**
   * Returns the meta object for the containment reference list '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.NaryAssociation#getEnds <em>Ends</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Ends</em>'.
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.NaryAssociation#getEnds()
   * @see #getNaryAssociation()
   * @generated
   */
  EReference getNaryAssociation_Ends();

  /**
   * Returns the meta object for class '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.AssociationEnd <em>Association End</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Association End</em>'.
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.AssociationEnd
   * @generated
   */
  EClass getAssociationEnd();

  /**
   * Returns the meta object for the attribute '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.AssociationEnd#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.AssociationEnd#getName()
   * @see #getAssociationEnd()
   * @generated
   */
  EAttribute getAssociationEnd_Name();

  /**
   * Returns the meta object for the containment reference '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.AssociationEnd#getMultiplicity <em>Multiplicity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Multiplicity</em>'.
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.AssociationEnd#getMultiplicity()
   * @see #getAssociationEnd()
   * @generated
   */
  EReference getAssociationEnd_Multiplicity();

  /**
   * Returns the meta object for the reference '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.AssociationEnd#getEndType <em>End Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>End Type</em>'.
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.AssociationEnd#getEndType()
   * @see #getAssociationEnd()
   * @generated
   */
  EReference getAssociationEnd_EndType();

  /**
   * Returns the meta object for class '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.Multiplicity <em>Multiplicity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Multiplicity</em>'.
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.Multiplicity
   * @generated
   */
  EClass getMultiplicity();

  /**
   * Returns the meta object for the attribute '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.Multiplicity#getLower <em>Lower</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Lower</em>'.
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.Multiplicity#getLower()
   * @see #getMultiplicity()
   * @generated
   */
  EAttribute getMultiplicity_Lower();

  /**
   * Returns the meta object for the attribute '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.Multiplicity#getUpper <em>Upper</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Upper</em>'.
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.Multiplicity#getUpper()
   * @see #getMultiplicity()
   * @generated
   */
  EAttribute getMultiplicity_Upper();

  /**
   * Returns the meta object for class '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.Generalization <em>Generalization</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Generalization</em>'.
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.Generalization
   * @generated
   */
  EClass getGeneralization();

  /**
   * Returns the meta object for the reference '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.Generalization#getSuper <em>Super</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Super</em>'.
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.Generalization#getSuper()
   * @see #getGeneralization()
   * @generated
   */
  EReference getGeneralization_Super();

  /**
   * Returns the meta object for the reference '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.Generalization#getSub <em>Sub</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Sub</em>'.
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.Generalization#getSub()
   * @see #getGeneralization()
   * @generated
   */
  EReference getGeneralization_Sub();

  /**
   * Returns the meta object for class '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.DependencyLink <em>Dependency Link</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dependency Link</em>'.
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.DependencyLink
   * @generated
   */
  EClass getDependencyLink();

  /**
   * Returns the meta object for the reference '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.DependencyLink#getFrom <em>From</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>From</em>'.
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.DependencyLink#getFrom()
   * @see #getDependencyLink()
   * @generated
   */
  EReference getDependencyLink_From();

  /**
   * Returns the meta object for the reference '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.DependencyLink#getTo <em>To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>To</em>'.
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.DependencyLink#getTo()
   * @see #getDependencyLink()
   * @generated
   */
  EReference getDependencyLink_To();

  /**
   * Returns the meta object for class '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.GeneralizationSet <em>Generalization Set</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Generalization Set</em>'.
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.GeneralizationSet
   * @generated
   */
  EClass getGeneralizationSet();

  /**
   * Returns the meta object for the attribute '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.GeneralizationSet#isIsDisjoint <em>Is Disjoint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is Disjoint</em>'.
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.GeneralizationSet#isIsDisjoint()
   * @see #getGeneralizationSet()
   * @generated
   */
  EAttribute getGeneralizationSet_IsDisjoint();

  /**
   * Returns the meta object for the attribute '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.GeneralizationSet#isIsComplete <em>Is Complete</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is Complete</em>'.
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.GeneralizationSet#isIsComplete()
   * @see #getGeneralizationSet()
   * @generated
   */
  EAttribute getGeneralizationSet_IsComplete();

  /**
   * Returns the meta object for the containment reference list '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.GeneralizationSet#getGeneralizations <em>Generalizations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Generalizations</em>'.
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.GeneralizationSet#getGeneralizations()
   * @see #getGeneralizationSet()
   * @generated
   */
  EReference getGeneralizationSet_Generalizations();

  /**
   * Returns the meta object for class '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.Stereotype <em>Stereotype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Stereotype</em>'.
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.Stereotype
   * @generated
   */
  EClass getStereotype();

  /**
   * Returns the meta object for the attribute '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.Stereotype#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.Stereotype#getName()
   * @see #getStereotype()
   * @generated
   */
  EAttribute getStereotype_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  OntoUMLArchiveFactory getOntoUMLArchiveFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.ModelImpl
     * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.OntoUMLArchivePackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Elments</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ELMENTS = eINSTANCE.getModel_Elments();

    /**
     * The meta object literal for the '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.ModelElementImpl <em>Model Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.ModelElementImpl
     * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.OntoUMLArchivePackageImpl#getModelElement()
     * @generated
     */
    EClass MODEL_ELEMENT = eINSTANCE.getModelElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL_ELEMENT__NAME = eINSTANCE.getModelElement_Name();

    /**
     * The meta object literal for the '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.ClassImpl <em>Class</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.ClassImpl
     * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.OntoUMLArchivePackageImpl#getClass_()
     * @generated
     */
    EClass CLASS = eINSTANCE.getClass_();

    /**
     * The meta object literal for the '<em><b>Is Abstract</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLASS__IS_ABSTRACT = eINSTANCE.getClass_IsAbstract();

    /**
     * The meta object literal for the '<em><b>Stereotype</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS__STEREOTYPE = eINSTANCE.getClass_Stereotype();

    /**
     * The meta object literal for the '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.RelationshipImpl <em>Relationship</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.RelationshipImpl
     * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.OntoUMLArchivePackageImpl#getRelationship()
     * @generated
     */
    EClass RELATIONSHIP = eINSTANCE.getRelationship();

    /**
     * The meta object literal for the '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.AssociationImpl <em>Association</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.AssociationImpl
     * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.OntoUMLArchivePackageImpl#getAssociation()
     * @generated
     */
    EClass ASSOCIATION = eINSTANCE.getAssociation();

    /**
     * The meta object literal for the '<em><b>Stereotype</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSOCIATION__STEREOTYPE = eINSTANCE.getAssociation_Stereotype();

    /**
     * The meta object literal for the '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.RegularAssociationImpl <em>Regular Association</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.RegularAssociationImpl
     * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.OntoUMLArchivePackageImpl#getRegularAssociation()
     * @generated
     */
    EClass REGULAR_ASSOCIATION = eINSTANCE.getRegularAssociation();

    /**
     * The meta object literal for the '<em><b>From</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REGULAR_ASSOCIATION__FROM = eINSTANCE.getRegularAssociation_From();

    /**
     * The meta object literal for the '<em><b>To</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REGULAR_ASSOCIATION__TO = eINSTANCE.getRegularAssociation_To();

    /**
     * The meta object literal for the '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.NaryAssociationImpl <em>Nary Association</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.NaryAssociationImpl
     * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.OntoUMLArchivePackageImpl#getNaryAssociation()
     * @generated
     */
    EClass NARY_ASSOCIATION = eINSTANCE.getNaryAssociation();

    /**
     * The meta object literal for the '<em><b>Ends</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NARY_ASSOCIATION__ENDS = eINSTANCE.getNaryAssociation_Ends();

    /**
     * The meta object literal for the '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.AssociationEndImpl <em>Association End</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.AssociationEndImpl
     * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.OntoUMLArchivePackageImpl#getAssociationEnd()
     * @generated
     */
    EClass ASSOCIATION_END = eINSTANCE.getAssociationEnd();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASSOCIATION_END__NAME = eINSTANCE.getAssociationEnd_Name();

    /**
     * The meta object literal for the '<em><b>Multiplicity</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSOCIATION_END__MULTIPLICITY = eINSTANCE.getAssociationEnd_Multiplicity();

    /**
     * The meta object literal for the '<em><b>End Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSOCIATION_END__END_TYPE = eINSTANCE.getAssociationEnd_EndType();

    /**
     * The meta object literal for the '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.MultiplicityImpl <em>Multiplicity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.MultiplicityImpl
     * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.OntoUMLArchivePackageImpl#getMultiplicity()
     * @generated
     */
    EClass MULTIPLICITY = eINSTANCE.getMultiplicity();

    /**
     * The meta object literal for the '<em><b>Lower</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MULTIPLICITY__LOWER = eINSTANCE.getMultiplicity_Lower();

    /**
     * The meta object literal for the '<em><b>Upper</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MULTIPLICITY__UPPER = eINSTANCE.getMultiplicity_Upper();

    /**
     * The meta object literal for the '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.GeneralizationImpl <em>Generalization</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.GeneralizationImpl
     * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.OntoUMLArchivePackageImpl#getGeneralization()
     * @generated
     */
    EClass GENERALIZATION = eINSTANCE.getGeneralization();

    /**
     * The meta object literal for the '<em><b>Super</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GENERALIZATION__SUPER = eINSTANCE.getGeneralization_Super();

    /**
     * The meta object literal for the '<em><b>Sub</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GENERALIZATION__SUB = eINSTANCE.getGeneralization_Sub();

    /**
     * The meta object literal for the '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.DependencyLinkImpl <em>Dependency Link</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.DependencyLinkImpl
     * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.OntoUMLArchivePackageImpl#getDependencyLink()
     * @generated
     */
    EClass DEPENDENCY_LINK = eINSTANCE.getDependencyLink();

    /**
     * The meta object literal for the '<em><b>From</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEPENDENCY_LINK__FROM = eINSTANCE.getDependencyLink_From();

    /**
     * The meta object literal for the '<em><b>To</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEPENDENCY_LINK__TO = eINSTANCE.getDependencyLink_To();

    /**
     * The meta object literal for the '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.GeneralizationSetImpl <em>Generalization Set</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.GeneralizationSetImpl
     * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.OntoUMLArchivePackageImpl#getGeneralizationSet()
     * @generated
     */
    EClass GENERALIZATION_SET = eINSTANCE.getGeneralizationSet();

    /**
     * The meta object literal for the '<em><b>Is Disjoint</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENERALIZATION_SET__IS_DISJOINT = eINSTANCE.getGeneralizationSet_IsDisjoint();

    /**
     * The meta object literal for the '<em><b>Is Complete</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENERALIZATION_SET__IS_COMPLETE = eINSTANCE.getGeneralizationSet_IsComplete();

    /**
     * The meta object literal for the '<em><b>Generalizations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GENERALIZATION_SET__GENERALIZATIONS = eINSTANCE.getGeneralizationSet_Generalizations();

    /**
     * The meta object literal for the '{@link it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.StereotypeImpl <em>Stereotype</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.StereotypeImpl
     * @see it.unibz.inf.ontouml.archive.ontoUMLArchive.impl.OntoUMLArchivePackageImpl#getStereotype()
     * @generated
     */
    EClass STEREOTYPE = eINSTANCE.getStereotype();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STEREOTYPE__NAME = eINSTANCE.getStereotype_Name();

  }

} //OntoUMLArchivePackage
