/*
 * generated by Xtext 2.12.0
 */
package it.unibz.inf.ontouml.archive.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractOntoUMLArchiveScopeProvider extends DelegatingScopeProvider {
}
