/**
 * generated by Xtext 2.12.0
 */
package it.unibz.inf.ontouml.archive.scoping;

import it.unibz.inf.ontouml.archive.scoping.AbstractOntoUMLArchiveScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class OntoUMLArchiveScopeProvider extends AbstractOntoUMLArchiveScopeProvider {
}
