/*
 * generated by Xtext 2.12.0
 */
package it.unibz.inf.ontouml.archive.tests

import com.google.inject.Inject
import it.unibz.inf.ontouml.archive.ontoUMLArchive.Model
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(OntoUMLArchiveInjectorProvider)
class OntoUMLArchiveParsingTest {
	@Inject
	ParseHelper<Model> parseHelper
	
	@Test
	def void loadModel() {
//		val result = parseHelper.parse('''
//			Hello Xtext!
//		''')
//		Assert.assertNotNull(result)
//		Assert.assertTrue(result.eResource.errors.isEmpty)
	}
}
