/*
 * generated by Xtext 2.12.0
 */
package it.unibz.inf.ontouml.archive


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class OntoUMLArchiveStandaloneSetup extends OntoUMLArchiveStandaloneSetupGenerated {

	def static void doSetup() {
		new OntoUMLArchiveStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
