/*
 * generated by Xtext 2.12.0
 */
package it.unibz.inf.ontouml.archive


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class OntoUMLArchiveRuntimeModule extends AbstractOntoUMLArchiveRuntimeModule {
	
	override bindIValueConverterService() {
		return OntoUMLArchiveValueConverter
	}
	
}
