/**
 * generated by Xtext 2.12.0
 */
package it.unibz.inf.ontouml.archive.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class OntoUMLArchiveDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
