/*
 * generated by Xtext 2.12.0
 */
package it.unibz.inf.ontouml.archive.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class OntoUMLArchiveAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("it/unibz/inf/ontouml/archive/parser/antlr/internal/InternalOntoUMLArchive.tokens");
	}
}
