/**
 * generated by Xtext 2.12.0
 */
package it.unibz.inf.ontouml.archive.ui.contentassist;

import it.unibz.inf.ontouml.archive.OntoUMLArchiveUtils;
import it.unibz.inf.ontouml.archive.ui.contentassist.AbstractOntoUMLArchiveProposalProvider;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class OntoUMLArchiveProposalProvider extends AbstractOntoUMLArchiveProposalProvider {
  @Override
  public void completeClass_Stereotypes(final EObject model, final Assignment assignment, final ContentAssistContext context, final ICompletionProposalAcceptor acceptor) {
    super.completeClass_Stereotypes(model, assignment, context, acceptor);
    Set<String> _expectedClassStereotypes = OntoUMLArchiveUtils.getExpectedClassStereotypes();
    for (final String str : _expectedClassStereotypes) {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("<<");
      _builder.append(str);
      _builder.append(">>");
      acceptor.accept(this.createCompletionProposal(_builder.toString(), context));
    }
  }
  
  @Override
  public void completeDirectedAssociation_Stereotypes(final EObject model, final Assignment assignment, final ContentAssistContext context, final ICompletionProposalAcceptor acceptor) {
    super.completeDirectedAssociation_Stereotypes(model, assignment, context, acceptor);
    Set<String> _expectedBinaryAssociationStereotypes = OntoUMLArchiveUtils.getExpectedBinaryAssociationStereotypes();
    for (final String str : _expectedBinaryAssociationStereotypes) {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("<<");
      _builder.append(str);
      _builder.append(">>");
      acceptor.accept(this.createCompletionProposal(_builder.toString(), context));
    }
  }
  
  @Override
  public void completeUndirectedAssociation_Stereotypes(final EObject model, final Assignment assignment, final ContentAssistContext context, final ICompletionProposalAcceptor acceptor) {
    super.completeUndirectedAssociation_Stereotypes(model, assignment, context, acceptor);
    Set<String> _expectedBinaryAssociationStereotypes = OntoUMLArchiveUtils.getExpectedBinaryAssociationStereotypes();
    for (final String str : _expectedBinaryAssociationStereotypes) {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("<<");
      _builder.append(str);
      _builder.append(">>");
      acceptor.accept(this.createCompletionProposal(_builder.toString(), context));
    }
  }
}
