/**
 * generated by Xtext 2.12.0
 */
package it.unibz.inf.ontouml.archive.tests;

import com.google.inject.Inject;
import it.unibz.inf.ontouml.archive.ontoUMLArchive.Model;
import it.unibz.inf.ontouml.archive.tests.OntoUMLArchiveInjectorProvider;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.testing.validation.ValidationTestHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.Extension;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(OntoUMLArchiveInjectorProvider.class)
@SuppressWarnings("all")
public class OntoUMLArchiveParsingTest {
  @Inject
  @Extension
  private ParseHelper<Model> _parseHelper;
  
  @Inject
  @Extension
  private ValidationTestHelper _validationTestHelper;
  
  @Test
  public void loadModel() {
  }
  
  @Test
  public void testConstraintDeclaration() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("class \"A\"; class \"B\";");
      _builder.newLine();
      _builder.append("association ");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("from [1..*] : \"A\" {\"\"}");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("to [1..*] : \"B\" {\"\",\"\",\"\"};");
      _builder.newLine();
      final Model m = this._parseHelper.parse(_builder);
      Assert.assertNotNull(m);
      this._validationTestHelper.assertNoErrors(m);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
